# Generated by Django 2.0 on 2017-12-27 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committment',
            new_name='Commitment',
        ),
    ]
